//Skeleton generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC2 login doctor', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC2 login doctor', async function() {
    await driver.get("https://proxy-portal-test.web.app/login")
    await driver.manage().window().setRect({ width: 1050, height: 1050 })
    await driver.wait(until.elementLocated(By.css("#email")), 30000).click()
    await driver.findElement(By.css("#email")).sendKeys("doctor@proxyqb.com")
    //or: await driver.findElement(By.css("input[id='email']")).sendKeys("doctor@proxyqb.com")
    //or: await driver.findElement(By.id("email")).sendKeys("doctor@proxyqb.com")
    await driver.findElement(By.css("#password")).click()
    await driver.findElement(By.css("#password")).sendKeys("Heslo123")
    //button "LOG IN"/"PŘIHLÁSIT":
    await driver.findElement(By.css("button[type='submit']")).click()
    //or: await driver.findElement(By.xpath("//button[contains(.,\'Log\')]")).click()
    //href="/users/me/profile":
    await driver.wait(until.elementLocated(By.css("a[testing-id='header']")), 30000)
    //menu - check all buttons:
    await driver.findElement(By.css("button[testing-id='dashboard']"))
    //optional:
    await driver.findElement(By.css("a[href='/dashboard']"))
    //check button "Doctors/Doktoři" not present:
    {
      const elements = await driver.findElements(By.css(".button[testing-id='doctors']"))
      assert(!elements.length)
    }
    await driver.findElement(By.css("button[testing-id='patients']"))
    await driver.findElement(By.css("button[testing-id='catalogs']"))
    //check button "Roles/Role" not present:
    {
      const elements = await driver.findElements(By.css(".button[testing-id='roles']"))
      assert(!elements.length)
    }
    await driver.findElement(By.css("button[testing-id='games']"))
    await driver.findElement(By.css("button[testing-id='rehabilitationPlans']"))
    await driver.findElement(By.css("button[testing-id='analytics']"))
    await driver.findElement(By.css("button[testing-id='changelog']"))
    //button "Logout"/"Odhlásit se":
    await driver.findElement(By.css("a[href='/logout']")).click()
    //check login form:
    await driver.wait(until.elementLocated(By.css("form[id='loginForm']")), 30000)
    //check button "LOG IN"/"PŘIHLÁSIT":
    await driver.wait(until.elementLocated(By.css("button[type='submit']")), 30000)
    //or: await driver.wait(until.elementLocated(By.xpath("//button[contains(.,\'Log\')]")), 30000)
  })
})
